---
- name: cacti
  hosts: cacti
  vars:
    cacti_server_config_database_default: cacti
    cacti_server_dependencies:
      - git
      - snmp
      - snmp-mibs-downloader
      - rrdtool
      - cron  
    cacti_server_install: []
    cacti_server_install_path:
     src: "{{ cacti_server_checkout_path }}"
     dest: /var/www/html/cacti
    cacti_server_checkout_path: /var/lib/ansible/cacti-server/checkouts/cacti
    cacti_server_default_owner: root
    cacti_server_default_group: root
    cacti_server_default_directory_mode: '0755'
    cacti_server_default_file_mode: '0644'

    cacti_server_user: www-data
    cacti_server_group: www-data

    cacti_server_config_file: "{{ cacti_server_checkout_path }}/include/config.php"
    cacti_server_poller_file: "{{ cacti_server_checkout_path }}/poller.php"

    cacti_server_hardened_directories:
      - resource/snmp_queries
      - resource/script_server
      - resource/script_queries
      - scripts
      - include/vendor/csrf

    cacti_server_checkout_repo: https://github.com/Cacti/cacti.git
    cacti_server_version: 1.2.24
    cacti_server_git_version: "release/{{ cacti_server_version }}"

    cacti_server_config_database_default: cacti
    cacti_server_config_database_hostname: localhost
    cacti_server_config_database_username: cacti
    cacti_server_config_database_password: cacti
    cacti_server_config_database_port: 3306

    cacti_server_config_url_path: /cacti/

    cacti_server_use_poller_php: true
    cacti_server_poller_interval: 5
  tasks:
    - include_tasks: tasks/main.yml
