---
- name: cacti
  hosts: cacti
  vars:
    cacti_server_config_database_default: cacti
    cacti_server_dependencies:
      - git
      - snmp
      - snmp-mibs-downloader
      - rrdtool
      - cron  
    cacti_server_install: []
    cacti_server_install_path:
     src: "{{ cacti_server_checkout_path }}"
     dest: /var/www/html/cacti
    cacti_server_checkout_path: /var/lib/ansible/cacti-server/checkouts/cacti
  tasks:
    - include_tasks: tasks/main.yml
